### ISSUE TITLE
circle ci の導入

### ISSUE THREAD

**Issue by cohki0305** [yu-croco/airbnb_clone#5]
circle ci 使うと、github 上でテスト実行してもらえるから便利ですよ！
1 つのレポジトリーだけなら無料でつかえます。
http://qiita.com/noboru_i/items/7d300eb63ae667bf8dc2

**Comment by yu-croco** [comment]
ご指摘ありがとうございます！
今夜あたりに入れてみます。

**Comment by yu-croco** [comment]
ひとまず、入れてみました！
https://pull-requests.slack.com/archives/C6JRT3B7F/p1502290372942694
